steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-95fcfc61-ea90-4e73-8c4/demo-repo/hola-api:$SHORT_SHA'
      - '.'

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/project-95fcfc61-ea90-4e73-8c4/demo-repo/hola-api:$SHORT_SHA'

  # Deploy (aplica los YAML y actualiza la imagen)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/'
      - '--image=us-central1-docker.pkg.dev/project-95fcfc61-ea90-4e73-8c4/demo-repo/hola-api:$SHORT_SHA'
      - '--location=us-central1'
      - '--cluster=hola-cluster'

images:
  - 'us-central1-docker.pkg.dev/project-95fcfc61-ea90-4e73-8c4/demo-repo/hola-api:$SHORT_SHA'
